### PR TITLE
Improve how we determine what to trigger

### PR DESCRIPTION
**Pull request by valeriat**
This pull request fixes issue #76

### CODE REVIEW

**Comment by valeriat** [comment]
How can I test this change? I already run tox.

**Comment by vaibhavmagarwal** [comment]
@valeria, I am not very familiar with how the build jobs and other jobs get triggered, I will let @armenzg review this patch. For basic testing, you can see whether scripts/trigger.py runs properly.
Eg:
python scripts/trigger.py --buildername "b2g_ubuntu64_vm cedar debug test gaia-js-integration-5" --dry-run --revision d2d9810cf8d7

**Comment by armenzg** [comment]
If she does not have LDAP credentials it becomes hard to test it.
I will review it and test it by the end of today.

**Comment by armenzg** [comment]
From looking at the code, I was assuming that we would need changes in _determine_trigger_objective(). It would not be possible for you to test this without LDAP credentials.
I wish we had a way to setup buildapi locally and have sample data.
Long long time ago I tried it and I had some of the DB dump in here:
http://people.mozilla.org/~armenzg/permanent/databases
but setting up buildapi is not something I managed to make it work.

**Comment by adusca** [comment]
Since determine_upstream_builder() of a build job returns itself, when we pass a build job to _determine_trigger_objective() it returns buildername, None.
I think we had the if condition because of the old associated_build_job.

**Comment by armenzg** [comment]
@valeriat ignore the comments about buildapi.
For the rest, did it make sense the remaining comments?

**Comment by armenzg** [comment]
Hi @valeriat 
Thanks for your help, however, I have fixed this code while I was doing some refactoring:
https://github.com/armenzg/mozilla_ci_tools/commit/d538e466ee4af69f8f7b7d09657efb41e27af9b0

Please have a look at https://github.com/armenzg/mozilla_ci_tools/issues for other issues to help with.

**Pull request closed without merging**
