### PR TITLE
Adding support to trigger talos jobs for a given build

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
@armenzg I hope it is okay

---

This change is [Reviewable](https://reviewable.io/reviews/mozilla/mozilla_ci_tools/470)

### CODE REVIEW

**Comment by martiansideofthemoon** [comment]
@armenzg this works for me locally I think. For the input `Linux x86-64 mozilla-inbound pgo-build`, I got the following talos jobs : 

```
u'Ubuntu HW 12.04 x64 mozilla-inbound pgo talos g1-e10s',
u'Ubuntu HW 12.04 x64 mozilla-inbound pgo talos dromaeojs',
u'Ubuntu HW 12.04 x64 mozilla-inbound pgo talos g1',
u'Ubuntu HW 12.04 x64 mozilla-inbound pgo talos g2',
u'Ubuntu HW 12.04 x64 mozilla-inbound pgo talos chromez-e10s',
u'Ubuntu HW 12.04 x64 mozilla-inbound pgo talos svgr-e10s',
u'Ubuntu HW 12.04 x64 mozilla-inbound pgo talos tp5o-e10s',
u'Ubuntu HW 12.04 x64 mozilla-inbound pgo talos svgr',
u'Ubuntu HW 12.04 x64 mozilla-inbound pgo talos g3',
u'Ubuntu HW 12.04 x64 mozilla-inbound pgo talos g2-e10s',
u'Ubuntu HW 12.04 x64 mozilla-inbound pgo talos chromez',
u'Ubuntu HW 12.04 x64 mozilla-inbound pgo talos tp5o',
u'Ubuntu HW 12.04 x64 mozilla-inbound pgo talos dromaeojs-e10s',
u'Ubuntu HW 12.04 x64 mozilla-inbound pgo talos other',
u'Ubuntu HW 12.04 x64 mozilla-inbound pgo talos g3-e10s',
u'Ubuntu HW 12.04 x64 mozilla-inbound pgo talos other-e10s'
```

and for the buildername `WINNT 5.2 mozilla-inbound pgo-build` I got,

```
Windows 7 32-bit mozilla-inbound pgo talos chromez
Windows 7 32-bit mozilla-inbound pgo talos chromez-e10s
Windows 7 32-bit mozilla-inbound pgo talos dromaeojs
Windows 7 32-bit mozilla-inbound pgo talos dromaeojs-e10s
Windows 7 32-bit mozilla-inbound pgo talos g1
Windows 7 32-bit mozilla-inbound pgo talos g1-e10s
Windows 7 32-bit mozilla-inbound pgo talos g2
Windows 7 32-bit mozilla-inbound pgo talos g2-e10s
Windows 7 32-bit mozilla-inbound pgo talos other
Windows 7 32-bit mozilla-inbound pgo talos other-e10s
Windows 7 32-bit mozilla-inbound pgo talos svgr
Windows 7 32-bit mozilla-inbound pgo talos svgr-e10s
Windows 7 32-bit mozilla-inbound pgo talos tp5o
Windows 7 32-bit mozilla-inbound pgo talos tp5o-e10s
Windows 7 32-bit mozilla-inbound pgo talos xperf
Windows 7 32-bit mozilla-inbound pgo talos xperf-e10s
Windows XP 32-bit mozilla-inbound pgo talos chromez
Windows XP 32-bit mozilla-inbound pgo talos chromez-e10s
Windows XP 32-bit mozilla-inbound pgo talos dromaeojs
Windows XP 32-bit mozilla-inbound pgo talos dromaeojs-e10s
Windows XP 32-bit mozilla-inbound pgo talos g1
Windows XP 32-bit mozilla-inbound pgo talos g1-e10s
Windows XP 32-bit mozilla-inbound pgo talos g2
Windows XP 32-bit mozilla-inbound pgo talos g2-e10s
Windows XP 32-bit mozilla-inbound pgo talos other
Windows XP 32-bit mozilla-inbound pgo talos other-e10s
Windows XP 32-bit mozilla-inbound pgo talos svgr
Windows XP 32-bit mozilla-inbound pgo talos svgr-e10s
Windows XP 32-bit mozilla-inbound pgo talos tp5o
Windows XP 32-bit mozilla-inbound pgo talos tp5o-e10s
```

**Comment by armenzg** [comment]
This patch looks pretty clean.

Could you please add few tests for this?

If you believe we need to have a version of allthethings.json in-disk and only keep the information we care about please go ahead. I can imagine it can get annoying to deal with mock_allthethings.json

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[mozci/mozci.py, line 579 [r4]](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/470#-KH5HzEPyeDsXTJu_xRW:-KH5HzEQby_vjQOX-F8x:-1989986015) ([raw file](https://github.com/mozilla/mozilla_ci_tools/blob/1a53285c56e75667e850cd4f6995ca553863b2fe/mozci/mozci.py#L579)):_
You don't need this extra_properties.

We _might_ use the extra_properties for something related to trigger-bot but of that I'm not sure.
This is code that vaibhav1994 landed a while back.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/470#-:-KH5IB_fpH0Hx1YLm2LU:-1862283877)_

**Comment by armenzg** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/470)_

**Comment by armenzg** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[mozci/mozci.py, line 566 [r5]](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/470#-KH6nzoC3mQ8jZ--gBTP:-KH6nzoC3mQ8jZ--gBTQ:-642083451) ([raw file](https://github.com/mozilla/mozilla_ci_tools/blob/9a7feed35053deaf19a14cdba12c21a7d223b47a/mozci/mozci.py#L566)):_
Even cleaner! I like it.

---

_[mozci/platforms.py, line 395 [r5]](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/470#-KH6o6t4gyk4jGzp2jXE:-KH6o6t4gyk4jGzp2jXF:1159745096) ([raw file](https://github.com/mozilla/mozilla_ci_tools/blob/9a7feed35053deaf19a14cdba12c21a7d223b47a/mozci/platforms.py#L395)):_
Thanks for putting this function in here. It looks better.

---

_[test/test_platforms.py, line 32 [r5]](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/470#-KH6oabN7mtaEhqi3co_:-KH6oabN7mtaEhqi3coa:1012146289) ([raw file](https://github.com/mozilla/mozilla_ci_tools/blob/9a7feed35053deaf19a14cdba12c21a7d223b47a/test/test_platforms.py#L32)):_
Thank you for making this more general.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/470)_

**Pull request merged**
