### PR TITLE
Added coveralls

### PR DESCRIPTION
**Pull request by adusca**
Please ignore this PR for now, I'm testing the coveralls integration.  I'll let you know when it is ready. I just wanted to see if this would make something show up in https://coveralls.io/r/armenzg/mozilla_ci_tools

### CODE REVIEW

**Comment by adusca** [comment]
Update: The badge still shows coverage unknown, but the latest build shows up with 12% coverage: https://coveralls.io/builds/2003260

**Comment by Callek** [comment]
Yea the badge won't show any coverage until this gets merged in

**Comment by Callek** [comment]
Also @armenzg the reason coveralls didn't report to Github status, is because of:

```
Source Not Available

The owner of this repo needs to re-authorize with Github; their OAuth credentials are no longer valid so the file cannot be pulled from the Github API.
```

(I got that when trying to view coverage for a single file)

**Comment by adusca** [comment]
I believe this is ready to be used.

**Pull request merged**
