### PR TITLE
Bug 1212004 - Handle when buildapi fails to submit a request

### PR DESCRIPTION
**Pull request by armenzg**
r?

We could have also added retry logic for now this is good enough (since at least we can recognize the status error).

https://bugzilla.mozilla.org/show_bug.cgi?id=1212004

### CODE REVIEW

**Comment by vaibhavmagarwal** [comment]
From the traceback, I think the ValueError is occurring only because of this line: `content = req.json()`
We are not using the `content` variable in the function, so can we just remove it? I think that will fix the ValueError, as the response may not always be a correctly formatted json.

**Comment by armenzg** [comment]
Hi @vaibhavmagarwal you're right that the exceptions comes from content = req.json(), however, I believe I moved the whole block since I was considering adding more exceptions from the post call (which I didn't).

Let me fix this.

contents is used a little below:
https://github.com/armenzg/mozilla_ci_tools/pull/356/files#diff-e9eac7c08694fea7da57a886c52ff7d6R64

**Comment by armenzg** [comment]
Is this better? r?

**Comment by vaibhavmagarwal** [comment]
r+
Just another query, should we retry posting it once instead of directly exiting? I believe that can be a bit better, but upto you.

**Comment by armenzg** [comment]
I've considered it but I did not want to go there since I really dislike the retry logic of requests.

I've considered adding the redo python package as a dependency but I did not want to increase the scope.

I will take this as-is as I want to bump the mozci version for another fix for pulse_actions.

**Pull request merged**
