### PR TITLE
Removing mock_allthethings.json for a better testing experience

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
ref #474 

This change is [Reviewable](https://reviewable.io/reviews/mozilla/mozilla_ci_tools/475)

### CODE REVIEW

**Comment by martiansideofthemoon** [comment]
@armenzg , I've tried my best to remove the mock file completely. There is one problem with this fix. There are two response files which need to be updated with time. (Assuming allthethings.json changes). What should be done about this?

**Comment by armenzg** [comment]
Thank you so much for this change!

There are a bunch of small changes in my comments.
Could you please also put any new files under the director test/fixtures?

<details><summary>

<i>Previously, martiansideofthemoon (Kalpesh Krishna) wrote…</i></summary>



> @armenzg , I've tried my best to remove the mock file completely. There is one problem with this fix. There are two response files which need to be updated with time. (Assuming allthethings.json changes). What should be done about this?</details>

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[tox.ini, line 29 [r1]](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475#-KHtjpa3cO0sp_SKTccc:-KHtjpa4KeChz7W3ykvC:-815345550) ([raw file](https://github.com/mozilla/mozilla_ci_tools/blob/e7960c310e07784c6eda7f6cb8f3515f5b72abfb/tox.ini#L29)):_

> ``` INI
> 
> commands =
>     wget https://secure.pub.build.mozilla.org/builddata/reports/allthethings.json -O ./test/allthethings.json
> ```

There is a flag that wget has to determine if the file already on disk is the same that we're trying to fetch. If it is the same it won't download it.

This is good for when we need to run tox more than once.

We also need to use a known non-changing target:
https://secure.pub.build.mozilla.org/builddata/reports/allthethings/allthethings.20160516060001._87b285bcdaf0_21165e565d41_186a28cf7485.json

Otherwise, running the tests could change from today to tomorrow depending on what releng lands.

We might want to have the new_deps tox environment to use the latest to help us catch regressions in advance.

I also get this warning when running tox:
WARNING:test command found but not installed in testenv
  cmd: /usr/bin/wget
  env: /home/armenzg/repos/ci_tools/.tox/py27_new_deps
Maybe you forgot to specify a dependency? See also the whitelist_externals envconfig setting.

Could you also download it under test/fixtures?

---

_[test/helpers.py, line 17 [r1]](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475#-KHtl72EWU5KmYnsnrF5:-KHtl72FeTNSvAQ6BSpO:-2023266183) ([raw file](https://github.com/mozilla/mozilla_ci_tools/blob/e7960c310e07784c6eda7f6cb8f3515f5b72abfb/test/helpers.py#L17)):_

> ``` Python
> 
> def _get_SETA():
>     """Loads allthethings.json from disk."""
> ```

Is this comment accurate?

---

_[test/SETA_result.json, line 0 [r1]](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475#-KHtqduPNdmZcmwEWPlE:-KHtqduQ5TZUS8A6uxyr:1273839125) ([raw file](https://github.com/mozilla/mozilla_ci_tools/blob/e7960c310e07784c6eda7f6cb8f3515f5b72abfb/test/SETA_result.json#L0)):_
How did you generate this file?

---

_[test/test_platforms.py, line 100 [r1]](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475#-KHts0ljPIji8r5r3Nkl:-KHts0lkVUxHDrtkiXbM:774026723) ([raw file](https://github.com/mozilla/mozilla_ci_tools/blob/e7960c310e07784c6eda7f6cb8f3515f5b72abfb/test/test_platforms.py#L100)):_

> ``` Python
>         fetch_allthethings_data.return_value = ALLTHETHINGS
>         obtained = sorted(find_buildernames(repo='try', platform='android-x86'))
>         expected = sorted([u'Android 4.2 x86 Emulator try opt test androidx86-set-4'])
> ```

Smart choice :+1: 

---

_[test/test_platforms.py, line 140 [r1]](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475#-KHtsiXA3GbziAfN-fS0:-KHtsiXA3GbziAfN-fS1:-841133853) ([raw file](https://github.com/mozilla/mozilla_ci_tools/blob/e7960c310e07784c6eda7f6cb8f3515f5b72abfb/test/test_platforms.py#L140)):_

> ``` Python
>         self.assertEquals(
>             get_SETA_interval_dict(),
>             SETA_RESULT
> ```

I'm surprised that this would work since the file SETA_results.json is not just one file.
Do we need a whole file for this test?

I get this:
______________________________________________________________________________________ TestSETA.test_parse_correctly _______________________________________________________________________________________

self = <test_platforms.TestSETA testMethod=test_parse_correctly>, fetch_allthethings_data = <MagicMock name='fetch_allthethings_data' id='139884587571984'>

```
@patch('mozci.platforms.fetch_allthethings_data')
def test_parse_correctly(self, fetch_allthethings_data):
    """get_SETA_interval_dict should return a dict with correct SETA intervals."""
    fetch_allthethings_data.return_value = ALLTHETHINGS
    self.assertEquals(
        get_SETA_interval_dict(),
```

> ```
>       SETA_RESULT
>     )
> ```
> 
> E       AssertionError: {u'Windows 7 32-bit fx-team opt test mochitest-devtools-chrome-7': [7, 3600], u' [truncated]... != {u'Windows 7 32-bit fx-team opt test mochitest-devtools-chrome-7': [7, 3600], u' [truncated]...
> E       Diff is 167173 characters long. Set self.maxDiff to None to see it.

test/test_platforms.py:140: AssertionError
========================================================================= 1 failed, 83 passed, 1 pytest-warnings in 13.26 seconds ==========================================================================
ERROR: InvocationError: '/home/armenzg/repos/ci_tools/.tox/py27_new_deps/bin/coverage run --source=mozci -m py.test test

---

_[test/test_platforms.py, line 316 [r1]](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475#-KHtzd8KQrpXDzsy0zjD:-KHtzd8KQrpXDzsy0zjE:714309808) ([raw file](https://github.com/mozilla/mozilla_ci_tools/blob/e7960c310e07784c6eda7f6cb8f3515f5b72abfb/test/test_platforms.py#L316)):_

> ``` Python
>         """Test if the function finds the right downstream jobs."""
>         fetch_allthethings_data.return_value = ALLTHETHINGS
>         jobs = sorted(get_downstream_jobs('Android armv7 API 15+ try build'))
> ```

Instead of jobs, could you please name it downstream_builders?

---

_[test/test_platforms.py, line 318 [r1]](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475#-KHtzxASge3xBH63AGsH:-KHtzxATE_Qs444HEeh4:1737603355) ([raw file](https://github.com/mozilla/mozilla_ci_tools/blob/e7960c310e07784c6eda7f6cb8f3515f5b72abfb/test/test_platforms.py#L318)):_

> ``` Python
>         jobs = sorted(get_downstream_jobs('Android armv7 API 15+ try build'))
>         test_result = True
>         some_expected = [
> ```

You could instead use this:
expected = GRAPH_RESULT['opt']['android-api-15']['Android armv7 API 15+ try build']

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475#-:-KHtxFTUvsMYEFXATveI:-1239715468)_

**Comment by martiansideofthemoon** [comment]
@armenzg r?
I think this is pretty much complete. I'm sorry, I don't remember the location of the JSON files you'd told me. Can you remind me?

**Comment by armenzg** [comment]
Could you use reviewable.io for this PR? It will help you see the issues I raised more easily.

Could you please move the new files under the directory test/fixtures?

<details><summary>

<i>Previously, martiansideofthemoon (Kalpesh Krishna) wrote…</i></summary>



> @armenzg r?
> 
> I think this is pretty much complete. I'm sorry, I don't remember the location of the JSON files you'd told me. Can you remind me?
> </details>

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[tox.ini, line 40 [r1]](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475#-KI3GLVnxjWIcFKY3eCw:-KI3GLVnxjWIcFKY3eCx:-1395699256) ([raw file](https://github.com/mozilla/mozilla_ci_tools/blob/e7960c310e07784c6eda7f6cb8f3515f5b72abfb/tox.ini#L40)):_

> ``` INI
> 
> commands =
>     wget https://secure.pub.build.mozilla.org/builddata/reports/allthethings.json -O ./test/allthethings.json
> ```

Why do you need a bash script? 

---

_[test/test_platforms.py, line 318 [r1]](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475#-KHtzxASge3xBH63AGsH:-KI3JBXwMBUulczZyd2H:-291769048) ([raw file](https://github.com/mozilla/mozilla_ci_tools/blob/e7960c310e07784c6eda7f6cb8f3515f5b72abfb/test/test_platforms.py#L318)):_
<details><summary>

<i>Previously, armenzg (Armen Zambrano) wrote…</i></summary>



> You could instead use this:
> expected = GRAPH_RESULT['opt']['android-api-15']['Android armv7 API 15+ try build']
> </details>
> This still needs addressing.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475#-:-KI3JFUvk90U8ra9hgHq:1846778291)_

**Comment by martiansideofthemoon** [comment]
Review status: 3 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

_[tox.ini, line 40 [r1]](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475#-KI3GLVnxjWIcFKY3eCw:-KI3_92plBRyxAEf8pEn:816550887) ([raw file](https://github.com/mozilla/mozilla_ci_tools/blob/e7960c310e07784c6eda7f6cb8f3515f5b72abfb/tox.ini#L40)):_
<details><summary>

<i>Previously, armenzg (Armen Zambrano) wrote…</i></summary>



> Why do you need a bash script? 
> </details>
> Because the `-nc` flag which checks whether the file exists, was stopping the `tox` script in the case the file existed

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475)_

**Comment by martiansideofthemoon** [comment]
I hope it is okay now.
@armenzg r?

<details><summary>

<i>Previously, armenzg (Armen Zambrano) wrote…</i></summary>



> Could you use reviewable.io for this PR? It will help you see the issues I raised more easily.
> 
> Could you please move the new files under the directory test/fixtures?
> </details>

---

Review status: 3 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475#-:-KI3aFTD7zu4hxIcqTyb:1375891276)_

**Comment by armenzg** [comment]
Only one more change :)

<details><summary>

<i>Previously, martiansideofthemoon (Kalpesh Krishna) wrote…</i></summary>



> I hope it is okay now.
> @armenzg r?
> </details>

---

Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[tox.ini, line 40 [r1]](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475#-KI3GLVnxjWIcFKY3eCw:-KI3hsgYIlgCt6g3x1rt:-2009323032) ([raw file](https://github.com/mozilla/mozilla_ci_tools/blob/e7960c310e07784c6eda7f6cb8f3515f5b72abfb/tox.ini#L40)):_
<details><summary>

<i>Previously, martiansideofthemoon (Kalpesh Krishna) wrote…</i></summary>



> Because the `-nc` flag which checks whether the file exists, was stopping the `tox` script in the case the file existed
> </details>
> You can do this instead:
> 
> ``` bash
>  commands =
> -    ./download.sh
> +    wget -N https://secure.pub.build.mozilla.org/builddata/reports/allthethings/allthethings.20160516060001._87b285bcdaf0_21165e565d41_186a28cf7485.json
> +    cp allthethings.20160516060001._87b285bcdaf0_21165e565d41_186a28cf7485.json test
>      flake8 mozci test
>      coverage run --source=mozci -m py.test test
> -    rm test/allthethings.json
> ```

It was due to a mixin of using -nc and -O

The extra rm at the end removed the advantage of running tox a second time and have a fast turn around of results.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475#-:-KI3iKctsZVGrdHWuXhD:9336253)_

**Comment by armenzg** [comment]
Just the change to rm and bash on tox.ini

<details><summary>

<i>Previously, armenzg (Armen Zambrano) wrote…</i></summary>



> Only one more change :)
> </details>

---

Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[tox.ini, line 16 [r4]](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475#-KI4iYijbUkJ3C2njmdX:-KI4iYijbUkJ3C2njmdY:-492780737) ([raw file](https://github.com/mozilla/mozilla_ci_tools/blob/1909d46d6ff1d99e2f58113414589f7603573b05/tox.ini#L16)):_

> ``` INI
>     rm
>     wget
>     bash
> ```

You don't need rm and bash anymore.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475#-:-KI4igl4ch7lbR7hDJw7:-258907773)_

**Comment by martiansideofthemoon** [comment]
removed them!

<details><summary>

<i>Previously, armenzg (Armen Zambrano) wrote…</i></summary>



> Just the change to rm and bash on tox.ini
> </details>

---

Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475#-:-KI4jCGA3JDeC99jRGlp:1711658208)_

**Comment by armenzg** [comment]
:lgtm:

<details><summary>

<i>Previously, martiansideofthemoon (Kalpesh Krishna) wrote…</i></summary>



> removed them!
> </details>

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/mozilla_ci_tools/475#-:-KI4k4M27G4TCQxBmkt9:1417088721)_

**Pull request merged**
