### PR TITLE
Added pytest to tox

### PR DESCRIPTION
**Pull request by adusca**

### CODE REVIEW

**Comment by armenzg** [comment]
You rock! Thanks Alice!

**Comment by vaibhavmagarwal** [comment]
@adusca : I get this error on running: https://pastebin.mozilla.org/8823437

**Comment by armenzg** [comment]
That's probably because we need py.test as part of the dependencies. Let me try.

**Comment by armenzg** [comment]
Nevermind my last comment!

What did you run?

**Comment by vaibhavmagarwal** [comment]
Pulled the latest changes and ran 'tox'

**Comment by armenzg** [comment]
Can you remove your venv?

**Comment by armenzg** [comment]
We probably need to _only_ run tests against test/

I think you can add a paremeter to py.test to _only_ run against test.

**Pull request merged**
