### PR TITLE
Experimenting triggering lists.

### PR DESCRIPTION
**Pull request by adusca**
In this branch the command 'python mozci/scripts/triggerbyfilters.py try fd4f1d879638 -i 'mochitest-1' -e android,b2g,pgo,10.8,coverage,asan --dry-run --times 7' takes 30 seconds [1], in master the same command takes 1 minute 52 seconds [2].

[1] https://pastebin.mozilla.org/8834016
[2] https://pastebin.mozilla.org/8834019

### CODE REVIEW

**Comment by adusca** [comment]
This first version adds a lot of repetition to the codebase, but I just wanted to see if it would be faster. 

Some results without --dry-run:

python mozci/scripts/triggerbyfilters.py try fd4f1d879638 -i 'mochitest-1' -e android,b2g,pgo,10.8,coverage,asan  --times 5 (14 jobs 5 times each)
takes 1:42 seconds in this branch and 2:35 in master 

python mozci/scripts/triggerbyfilters.py try fd4f1d879638 -i 'mochitest' -e android,b2g,pgo,10.8,coverage,asan,chrome,debug (73 jobs 1 time each)
takes 2:46 in this branch and 5:01 in master

I don't know if this improvement is enough to pursue.

**Comment by armenzg** [comment]
We see some great improvements with your changes, however, I would be more interested on caching or keeping track of the status of jobs.
I think the most expensive calls are:
all_jobs = query_jobs(repo_name, revision)
status = buildapi.query_job_status(job)

I think profiling could help us spot the functions that take the longest.
Otherwise, we're speculating.

When you say 1:42 seconds; is that 1 minute and 42 seconds?

We could optimize things a bit more if we remember the status of the build jobs that we have already inspected for status rather than for every buildername that it triggers (i.e. all android test jobs are triggered by the same build job).

We wouldn't have to have to look for the status as often as we do now:
 build_buildername = determine_upstream_builder(buildername)
 build_jobs = _matching_jobs(build_buildername, all_jobs)
 for job in build_jobs
    status = buildapi.query_job_status(job)

**Comment by adusca** [comment]
I'm exploring to find out where the speed gains come from. I have a branch that just adds caching to query_jobs[1].

Timing the command "python mozci/scripts/triggerbyfilters.py try 443657964b30 -i 'mochitest-1' -e android,b2g,pgo,10.8,coverage,asan --dry-run --times 7"

master:  2 minutes 1 second
caching: 1 minute 4 seconds
this branch: 36 seconds

I have no idea why this branch is faster then with caching. I'll investigate further.

[1] https://github.com/armenzg/mozilla_ci_tools/compare/master...adusca:cache-jobs

**Comment by adusca** [comment]
I ran again with cProfile, results organized by total time spent with a function (I didn't paste anything under 0.01s):

master: https://pastebin.mozilla.org/8834194
caching: https://pastebin.mozilla.org/8834191
this branch: https://pastebin.mozilla.org/8834196

The big difference is in the time spent in networking stuff. One example: the method 'do_handshake' of 'OpenSSL.SSL.Connection' takes about 0.6s. On master the method is called 85 times, 31 on caching and just 4 on this branch.

**Comment by adusca** [comment]
I used gprof2dot with cProfile's results and discovered that a big bottleneck in the caching branch was valid_revision in buildapi. I added a new cache to that function and now the caching branch is faster than this one, so I'm closing this PR. (I'll open a new PR from the caching branch)

**Pull request closed without merging**
